services:
  db:
    image: postgres:16
    container_name: syachosyogi_db
    restart: always
    environment:
      POSTGRES_USER: syachosyogi
      POSTGRES_PASSWORD: syachosyogi
      POSTGRES_DB: syachosyogi
    ports:
      - "5432:5432"
    volumes:
      - syachosyogi_db_data:/var/lib/postgresql/data

  api:
    image: ghcr.io/takumi1120/syachosyogi-api:latest
    container_name: syachosyogi_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://syachosyogi:syachosyogi@db:5432/syachosyogi?schema=public
      CORS_ORIGIN: http://54.252.188.39
      PORT: 3000
    ports:
      - "3000:3000"

  web:
    image: ghcr.io/takumi1120/syachosyogi-web:latest
    container_name: syachosyogi_web
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"

  gobdb:
    image: postgres:16
    container_name: gob_db
    restart: always
    environment:
      POSTGRES_USER: gob
      POSTGRES_PASSWORD: gob1234
      POSTGRES_DB: gob
    ports:
      - "5433:5432"
    volumes:
      - gob_db_data:/var/lib/postgresql/data

  gobapi:
    image: ghcr.io/takumi1120/syacho-gobblet-api:latest
    container_name: gob_api
    restart: always
    depends_on:
      - gobdb
    environment:
      DATABASE_URL: postgresql://gob:gob1234@gobdb:5432/gob?schema=public
      CORS_ORIGIN: http://54.252.188.39:8080
      PORT: 3000
    ports:
      - "3001:3000"

  gobweb:
    image: ghcr.io/takumi1120/syacho-gobblet-web:latest
    container_name: gob_web
    restart: always
    depends_on:
      - gobapi
    ports:
      - "8080:80"

volumes:
  syachosyogi_db_data:
  gob_db_data: